"""a={1,5,7,8,3}
print(a.add(4))
print(a)
print(a.pop(),a)
print(a.discard(8),a)
#print(a.remove(2),a)"""
#a={2,3,4,5}
#b={4,7,8}
#print(a.union(b),a,b)
#print(a.update(b),a,b)
#print(a.intersection(b),a,b)
#print(a.intersection_update(b),a,b)
#print(a.difference(b),a,b)
#print(a.difference_update(b),a,b)
#print(a.symmetric_difference(b),a,b)
#print(a^b)
#print(a.symmetric_difference_update(b),a,b)
a={2,3,4,5}
b={8,9}
"""print(a>=b)
print(a>b)
print(a.issupperset)"""
print(a.isdisjoint(b))
